server:
  port: 9001

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/public-library

management:
  endpoints:
    web:
      exposure:
        include: "*"
